FROM alpine:latest

RUN apk update && \
    apk add --no-cache nginx

RUN mkdir -p /var/www/app /run/nginx && \
    echo "<h1>Application Deployed via Terraform IaC!</h1>" > /var/www/app/index.html

RUN printf 'server {\n\
    listen 80;\n\
    root /var/www/app;\n\
    index index.html;\n\
    location / {\n\
        try_files $uri $uri/ =404;\n\
    }\n\
}\n' > /etc/nginx/http.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
